### ISSUE TITLE
Exception handling break when ZO+ enabled and php_sapi_name() method called

### ISSUE THREAD

**Issue by joebowmanedr** [zendtech/ZendOptimizerPlus#195] opened 2014-11-19 13:12 UTC
The following reduced case describes a bug:

```
if(php_sapi_name() === 'cli') {   // change this to !== 'cli' to replicate under PHP-FPM.
        try { // 1
             	try { // 2
                        throw new Exception('Raaaa');
                } catch (Exception $e) { // 2
                        echo 'hello';
                        throw $e;
                }
        } catch (Exception $e1) { // 1
                // squash
        }
}
```

Expected: 
* 'hello' echoed.
* Exception squashed.

Actual:
* On first run after enabling / clearing / invalidating (by updating doc) OpCache, acts as expected.
* Subsequent runs, the re-thrown exception never gets caught in lower catch logic, and is caught by exception handler instead.

This isn't limited to cli mode (also happens under php-fpm), but requires the call to `php_sapi_name()` and ZO+ 7.0.4-dev to be enabled for the appropriate SAPI.

This worked correctly under 7.0.3-dev. Turning off ZO+ causes the script to behave as expected.

Env: PHP 5.6.3 (PHP-FPM) on RHEL 6.4.

**Comment by laruence** [comment] 2015-01-08 05:52
I confirmed this bug with Derick yesterday.  and also got the root cause. will fix it soon, thanks :)

**Comment by laruence** [comment] 2015-01-09 04:01
fixed in https://github.com/php/php-src/commit/0547edb5c239a8cbfb7a1d16d85ee365480527dd

**Closed by laruence** 2015-01-09 04:01 UTC
Labels: bug
